hjhk

diff --git a/.github/workflows/ci_cd_test_environment.yml b/.github/workflows/ci_cd_test_environment.yml
--- a/.github/workflows/ci_cd_test_environment.yml
+++ b/.github/workflows/ci_cd_test_environment.yml
@@ -41,14 +41,17 @@ jobs:
 
     - name: Build and push Docker image
       id: build_image
-      env:
-        DOMAIN_NAME: ${{ vars.DOMAIN_NAME_1 }}
       run: |
+        export DOMAIN_NAME=${{ vars.DOMAIN_NAME_1 }}
+        if [ -z "$DOMAIN_NAME" ]; then
+            echo "::ERROR: 'DOMAIN_NAME_1' ENV VARIABLE IS EMPTY! PLEASE SET THIS VARIABLE"
+            exit 1
+        fi
+        envsubst '$DOMAIN_NAME' < domain.conf.template > default.conf
+        envsubst '$DOMAIN_NAME' < Dockerfile.template > Dockerfile.server
         IMAGE_TAG=${GITHUB_SHA::7}
         echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
         echo "Building image with tag ${IMAGE_TAG}"
-        envsubst '$DOMAIN_NAME' < domain.conf.template > default.conf
-        envsubst '$DOMAIN_NAME' < Dockerfile.template > Dockerfile.server
         docker build . -f Dockerfile.server -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:${IMAGE_TAG}
         echo "Pushing image ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:${IMAGE_TAG}"
         docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:${IMAGE_TAG}
