.

diff --git a/.github/workflows/ci_development_environment.yml b/.github/workflows/ci_development_environment.yml
--- a/.github/workflows/ci_development_environment.yml
+++ b/.github/workflows/ci_development_environment.yml
@@ -22,11 +22,11 @@ jobs:
       run: npm install
     - name: Run tests
       run: npm testaaaa
-    - name: Determine job status
-      if: always()
-      run: |
-        job_status=$([[ ${{ steps.execute.outcome }} == 'success' ]] && echo "success" || echo "failure")
-        echo "::set-output name=job_status::$job_status"
+    # - name: Determine job status
+    #   if: always()
+    #   run: |
+    #     job_status=$([[ ${{ steps.execute.outcome }} == 'success' ]] && echo "success" || echo "failure")
+    #     echo "::set-output name=job_status::$job_status"
 
   docker_build:
     if: >
@@ -57,13 +57,13 @@ jobs:
         docker build . -f Dockerfile.server -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:${IMAGE_TAG}
         echo "Pushing image ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:${IMAGE_TAG}"
         docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:${IMAGE_TAG}
-    - name: Determine job status
-      if: always()
-      run: |
-        job_status=$([[ ${{ steps.execute.outcome }} == 'success' ]] && echo "success" || echo "failure")
-        echo "::set-output name=job_status::$job_status"
+    # - name: Determine job status
+    #   if: always()
+    #   run: |
+    #     job_status=$([[ ${{ steps.execute.outcome }} == 'success' ]] && echo "success" || echo "failure")
+    #     echo "::set-output name=job_status::$job_status"
 
-  Approval:
+  Merge_approval:
     runs-on: ubuntu-latest
     environment:
       name: approval_merge_develop_branch
@@ -71,22 +71,22 @@ jobs:
       - name: Wait for merge approval 
         run: echo "Waiting for admin merge approval..."
 
-  check_merge_permission:
-    runs-on: ubuntu-latest
-    needs: [test, docker_build, Approval]
-    if: always()
-    steps:
-      - name: Check all jobs status and decide the final state
-        run: |
-          test_status="${{ needs.test.outputs.job_status }}"
-          docker_build_status="${{ needs.docker_build.outputs.job_status }}"
+  # check_merge_permission:
+  #   runs-on: ubuntu-latest
+  #   needs: [test, docker_build, Merge_approval]
+  #   if: always()
+  #   steps:
+  #     - name: Check all jobs status and decide the final state
+  #       run: |
+  #         test_status="${{ needs.test.outputs.job_status }}"
+  #         docker_build_status="${{ needs.docker_build.outputs.job_status }}"
 
-          echo "Docker build status: $docker_build_status"
-          echo "Test status: $test_status"
+  #         echo "Docker build status: $docker_build_status"
+  #         echo "Test status: $test_status"
 
-          if [[ "$docker_build_status" != "success" || "$test_status" != "success" ]]; then
-            echo "One or more jobs didn't succeed."
-            exit 1
-          else
-            echo "All jobs succeeded."
-          fi
+  #         if [[ "$docker_build_status" != "success" || "$test_status" != "success" ]]; then
+  #           echo "One or more jobs didn't succeed."
+  #           exit 1
+  #         else
+  #           echo "All jobs succeeded."
+  #         fi
