a

diff --git a/.github/workflows/deploy_development.yml b/.github/workflows/deploy_development.yml
--- a/.github/workflows/deploy_development.yml
+++ b/.github/workflows/deploy_development.yml
@@ -55,8 +55,16 @@ jobs:
     - name: Extract server number
       id: target_server
       run: |
-        echo "SERVER_NUMBER=$(echo ${{ github.event.comment.body }} | grep -o -E 's[0-9]+' | cut -c2-)" >> $GITHUB_ENV
-        echo "SERVER_NUMBER=$(echo ${{ github.event.comment.body }} | grep -o -E 's[0-9]+' | cut -c2-)" >> $GITHUB_OUTPUT
+        SERVER_NUMBER=$(echo ${{ github.event.comment.body }} | grep -o -E 's[0-9]+' | cut -c2-)
+
+        if [ -z "$SERVER_NUMBER" ]; then
+            echo "ERROR:: Command is incorrect!"
+            exit 1
+        fi
+
+        echo "SERVER_NUMBER=$SERVER_NUMBER" >> $GITHUB_ENV
+        echo "SERVER_NUMBER=$SERVER_NUMBER" >> $GITHUB_OUTPUT
+
 
     - name: Create env file
       run: echo "${{ secrets.ENV_FILE }}" > .env
@@ -70,13 +78,17 @@ jobs:
         DOMAIN_KEY_NAME: ${{ format('DOMAIN_NAME_{0}', env.SERVER_NUMBER) }}
 
       run: |
+        export DOMAIN_NAME=${{ vars[env.DOMAIN_KEY_NAME] }}
+        if [ -z "$SERVER_NUMBER" ]; then
+            echo "::ERROR: SERVER '$SERVER_NUMBER' NOT FOUND!"
+            exit 1
+        fi
+        envsubst '$DOMAIN_NAME' < domain.conf.template > default.conf
+        envsubst '$DOMAIN_NAME' < Dockerfile.template > Dockerfile.server
         TEMP_MERGE_COMMIT=$(git rev-parse HEAD)
         IMAGE_TAG=$(echo $TEMP_MERGE_COMMIT | cut -c 1-7)
         echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_OUTPUT
         echo "Building image with tag ${IMAGE_TAG}"
-        export DOMAIN_NAME=${{ vars[env.DOMAIN_KEY_NAME] }}
-        envsubst '$DOMAIN_NAME' < domain.conf.template > default.conf
-        envsubst '$DOMAIN_NAME' < Dockerfile.template > Dockerfile.server
         docker build . -f Dockerfile.server -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:${IMAGE_TAG}
         echo "Pushing image ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:${IMAGE_TAG}"
         docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:${IMAGE_TAG}
